change run command

diff --git a/run b/run
--- a/run
+++ b/run
@@ -5,53 +5,55 @@ if [[ ! -f django/local.env ]]; then
   echo "# Add environment variables here" > django/local.env
 fi
 
-case $1 in
-  dummydata )
+for arg; do case $arg in
+  help )
+    echo "usage: prod | dev | fake | fetchdb | build | webpack | up"
+    exit 0
+    ;;
+  prod )
+    echo "production settings"
+    export COMPOSE_FILE=docker-compose.yml:docker-compose.production.yml
+    ;;
+  dev )
+    echo "development settings"
+    unset COMPOSE_FILE
+    ;;
+  fake )
+    echo "populating database with fake data"
     docker-compose run --rm web django-admin fake_content -c10 -s50
     ;;
+  fetchdb )
+    set -e
+    SERVER=universitas.no
+    DB=www_universitas_no
+    echo "creating db dump from server $SERVER"
+    ssh $SERVER "sudo -u postgres pg_dump --no-owner -d $DB -f /tmp/dbdump.sql"
+    echo "copying db dump from server"
+    rsync --progress -az $SERVER:/tmp/dbdump.sql django/dbdump.sql
 
-  init )
+    # loading data
+    docker-compose down
+    docker-compose run --rm web load_db
+
+    # cleanup
+    ssh $SERVER "sudo rm /tmp/dbdump.sql"
+    rm /django/dbdump.sql
+    echo "done"
+    ;;
+  build )
     docker-compose down
     echo "building"
-    export COMPOSE_FILE=docker-compose.yml:docker-compose.production.yml
     docker-compose build
     docker-compose run --rm web django-admin migrate
     docker-compose run --rm web django-admin collectstatic --noinput
     ;;
-
   webpack )
-    export COMPOSE_FILE=docker-compose.yml:docker-compose.production.yml
     docker-compose run --rm webpack build
     ;;
-
-  fetchdb )
-    echo "fetching db dump"
-    ssh universitas.no "sudo -upostgres pg_dump --no-owner -dwww_universitas_no -f /tmp/dbdump.sql"
-    echo "copying db dump from server"
-    rsync --progress -az universitas.no:/tmp/dbdump.sql django/dbdump.sql
-    ssh universitas.no "sudo rm /tmp/dbdump.sql"
+  up )
+    echo "running webserver"
     docker-compose down
-    docker-compose run --rm web load_db
-    rm /django/dbdump.sql
-    ;;
-
-  prod )
-    docker-compose down
-    echo "running universitas production"
-    export COMPOSE_FILE=docker-compose.yml:docker-compose.production.yml
     docker-compose up -d
     ;;
-
-  dev )
-    docker-compose down
-    echo "running universitas development"
-    unset COMPOSE_FILE
-    docker-compose up
-    ;;
-
-  * )
-    echo "usage $0 init | prod | dev | fetchdb | webpack"
-    exit 1
-    ;;
-esac
+esac; done
 docker ps
